platform :ios, '9.0'
use_frameworks!

target "Example" do
  pod 'FWFramework', :path => '../', :subspecs => ['Framework', 'Component', 'Application', 'Authorize-Contacts', 'Authorize-Microphone', 'Authorize-Calendar', 'Authorize-AppleMusic']
  pod 'FWDebug', :configurations => ['Debug']
end

