platform :ios, '9.0'
use_frameworks!

target "Example" do
  pod 'FWFramework', :path => '../', :subspecs => ['Framework', 'Component', 'Application', 'Component-Contacts', 'Component-Microphone', 'Component-Calendar', 'Component-AppleMusic', 'Component-SDWebImage']
  pod 'FWDebug', :configurations => ['Debug']
end

