# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Pgyer"
  lane :pgyerbeta do
    # export_method: app-store、ad-hoc、development、enterprise
    build_app(export_method: "ad-hoc")
    pgyer(api_key: "{api_key}", user_key: "{user_key}", password: "{password}", install_type: "2", update_description: "{update_description}")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Example.xcodeproj")
    build_app(workspace: "Example.xcworkspace", scheme: "Example")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Example.xcodeproj")
    build_app(workspace: "Example.xcworkspace", scheme: "Example")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
