use_frameworks!
platform :ios, '9.0'

target 'User_Example' do
  pod 'User', :path => '../'
  pod 'Mediator', :path => '../../Mediator/'
  pod 'Core', :path => '../../Core/'
  pod 'Test', :path => '../../Test/'
  pod 'FWFramework', :path => '../../../../'
end
